# Generated by Django 4.2.7 on 2023-12-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzer', '0002_gamehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glevel', models.PositiveSmallIntegerField()),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('total_time', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
